# The admin password for the Keycloak master realm
keycloak_admin_password: "{{ lookup('password', '.secrets/{{ ansible_user }}/keycloak_admin_password', length = 8, chars = ['ascii_letters', 'digits']) }}"

# The password for the Harbor admin account
harbor_admin_password: "{{ lookup('password', '.secrets/{{ ansible_user }}/harbor_admin_password', length = 8, chars = ['ascii_letters', 'digits']) }}"

# The admin password for Azimuth administrative dashboards
admin_dashboard_ingress_basic_auth_password: "{{ lookup('password', '.secrets/{{ ansible_user }}/admin_dashboard_ingress_basic_auth_password', length = 8, chars = ['ascii_letters', 'digits']) }}"

# The secret key for signing Azimuth cookies
azimuth_secret_key: "{{ lookup('password', '.secrets/{{ ansible_user }}/azimuth_secret_key', length = 16, chars = ['ascii_letters', 'digits']) }}"
# The secret key for signing Zenith registrar tokens
zenith_registrar_subdomain_token_signing_key: "{{ lookup('password', '.secrets/{{ ansible_user }}/zenith_registrar_subdomain_token_signing_key', length = 32, chars = ['ascii_letters', 'digits']) }}"
# The secret key for Harbor
harbor_secret_key: "{{ lookup('password', '.secrets/{{ ansible_user }}/harbor_secret_key', length = 16, chars = ['ascii_letters', 'digits']) }}"
