# Use an infra name that is specific to our environment
# This is required because we are sharing an OpenStack project with several Azimuths
# Normally, this would not need to be set
infra_name: "azimuth-{{ '{{' }} azimuth_environment {{ '}}' }}{{ '{:0>2}'.format(user_idx + 1) }}"

# Use the local backend for Terraform - NOT RECOMMENDED FOR PRODUCTION
terraform_backend_type: local

# The floating IP to use for the Azimuth AIO
infra_fixed_floatingip: "{{ azops_training_infra_fixed_floatingip }}"

# The external network to use
infra_external_network_id: "{{ azops_training_infra_external_network_id }}"

{% if azops_training_infra_network_id %}
# The network to put the Azimuth AIO on
infra_network_id: "{{ azops_training_infra_network_id }}"
{% endif %}

# The flavor to use for the Azimuth AIO node
infra_flavor_id: "{{ azops_training_infra_flavor_id }}"

# Upload images as private - NOT RECOMMENDED FOR PRODUCTION
# By default Azimuth uploads images as "community" visibility, which means other tenants can see them
# Because this is a training environment, we instead upload as private
community_images_default_visibility: private
# Don't update the visibility of existing images that we find
community_images_update_existing_visibility: false

# Use a base domain from a dynamic DNS service that is derived from our floating IP
ingress_base_domain: "apps.{{ azops_training_infra_fixed_floatingip | replace('.', '-') }}.sslip.io"

# Disable TLS to avoid potential rate limiting by Let's Encrypt - NOT RECOMMENDED FOR PRODUCTION
ingress_tls_enabled: false

# The name of the cloud
azimuth_current_cloud_name: training
