---

- name: Install dependencies
  apt:
    update_cache: yes
    name:
      # Required to allow one unprivileged user to become another unprivileged user
      # https://docs.ansible.com/ansible-core/2.16/playbook_guide/playbooks_privilege_escalation.html#risks-of-becoming-an-unprivileged-user
      - acl
      # Dependencies for running Azimuth provisions
      - gcc
      - jq
      - python3
      - python3-dev
      - python3-venv
      - software-properties-common
      - zip
    state: present

- name: Create training group
  group:
    name: "{{ azops_training_group_name }}"

- name: Allow SSH password authentication for users in training group
  copy:
    dest: /etc/ssh/sshd_config.d/99-azops-training-allow-password.conf
    content: |
      Match Group {{ azops_training_group_name }}
          PasswordAuthentication yes
      Match all
  register: setup_users_sshd_config

- name: Restart SSHD
  service:
    name: sshd
    state: restarted
  when: setup_users_sshd_config is changed

- name: Create training users
  user:
    name: "{{ user.username }}"
    password: "{{ user.password | password_hash(salt = azops_training_password_salt) }}"
    shell: /usr/bin/bash
    groups:
      - "{{ azops_training_group_name }}"
  loop: "{{ azops_training_users }}"
  loop_control:
    loop_var: user
    label: "{{ user.username }}"
